#!/bin/sh


cd {u1.src_dir}
# When run from the host against the u1 guest:
# sudo apt-get install python-mocker
# scp ubuntu@{u1.address}:~/ubuntuone-servers/configs/local.conf configs/local.conf 
# scp ubuntu@{u1.address}:~/ubuntuone-servers/servers/u1servers/web/localsettings.py servers/u1servers/web/localsettings.py
# TODO ask on #u1-ops if there's a better way.
# sed -i 's/development-lazr.conf/local.conf/g' utilities/supervisor-dev.conf.tpl
# sed -i 's/development-appserver-lazr.conf/local.conf/g' utilities/supervisor-dev.conf.tpl
# echo 9999 >tmp/statsd.port
# make update-sourcedeps
U1CONFIG=`pwd`/configs/local.conf make smoke-test
U1CONFIG=`pwd`/configs/local.conf make acceptance-test
