#!/bin/sh -ex

# Allow ssh access to launchpad.
# This should probably be provided by setup_vm. -- vila 2013-03-10
ssh-keyscan bazaar.launchpad.net >>~/.ssh/known_hosts
# Get the branch.
bzr branch lp:curucu {curucu.src_dir}
# Setup the environment.
cd {curucu.src_dir}
# Set up the correct configuration.
# TODO we need an amazon key. --elopio - 2013-06-01
cat <<EOF >try.cfg
[amazon]
key = amazon key
secret = amazon secret

[feedback_store]
interval = 4
# when set to empty storing feedback is disabled
store_directory =

EOF
cat <<EOF >>configs/development-lazr.conf

[u1ms]
server: {music_search.url}

EOF
SOURCEDEPS_DIR=../ubunet-sourcedeps/ make
