#!/bin/sh -ex

# We can use U1_DEBUG=True to get debug messages on the console.
USSOC_SERVICE_URL={sso.url}/api/1.0/ /usr/lib/ubuntu-sso-client/ubuntu-sso-login &
# XXX ugly sleep.
sleep 5s
# TODO in order for the application to be accessible with testability, we need
# TESTABILITY=1
export SSO_AUTH_BASE_URL={sso.url}
export SSO_UONE_BASE_URL={u1.url}
/usr/lib/ubuntu-sso-client/ubuntu-sso-login-qt