#!/bin/sh -ex

# Allow ssh access to launchpad.
# This should probably be provided by setup_vm. -- vila 2013-03-10
ssh-keyscan bazaar.launchpad.net >>~/.ssh/known_hosts
# Get the branch.
bzr branch lp:canonical-identity-provider {sso.src_dir}
# Get the download cache.
bzr branch lp:~canonical-isd-hackers/+junk/download-cache
# Setup the environment.
cd {sso.src_dir}
# Get the version controlled configs.
bzr branch lp:~canonical-isd-hackers/isd-configs/sso-config branches/project
# Bootstrap the dependencies
fab bootstrap:download_cache_path=~/download-cache
# Set up the correct Django configuration.
# In order to set the db_host to a directory in .env, we need to use the full
# path. Otherwise, fab setup_postgresql_server will fail.
# TODO we can either configure the postgresql authentication and pass db_host
# as empty, or use cat just to append to the end of the default local.cfg
# that will contain the full path we need, or pass the user name in a config
# variable.
cat <<EOF >django_project/local.cfg
[__noschema__]
basedir = .
db_host = /home/ubuntu/{sso.src_dir}/.env/db
hostname = {sso.address}:{sso.port}

[__main__]
includes =
    config/devel.cfg
    ../branches/project/config/acceptance-dev.cfg

[django]
debug = false
email_port = {sso.smtp_port}

[testing]
imap_server = {sso.address}
imap_port = {sso.imap_port}
# needs to be a full email
imap_username = whatever@we.dont.care
imap_use_ssl = False

EOF
