#!/bin/sh

cd ~/{sso.src_dir}
# We need an SMTP server to send emails.
.env/bin/twistd localmail --imap {sso.imap_port} --smtp {sso.smtp_port}

# Setup the database.
fab setup_postgresql_server
fab manage:loaddata,test
fab manage:create_test_team
# get gargoyle flags from their use in the code
SST_FLAGS=`grep -rho --exclude 'test_*.py' "is_active([\"']\(.*\)[\"']" identityprovider/ webui/ | sed -E "s/is_active\(['\"](.*)['\"]/\1/" | awk '{print tolower($0)}' | sort | uniq | tr '\n' ','`
# We need to remove the trailing ','
fab gargoyle_flags:${SST_FLAGS%,}
# Start the SSO server, accessible from the local network.
fab run:0.0.0.0:{sso.port}
