#!/bin/sh

cd ~/{sso.src_dir}
# We need an SMTP server to send emails.
.env/bin/twistd localmail --imap {sso.imap_port} --smtp {sso.smtp_port}

# Setup the database.
fab setup_postgresql_server
fab manage:loaddata,allow_unverified
# Set the allow-unverified config for Pay.
fab manage:add_openid_rp_config,{pay.url},--allow-unverified,--allowed-user-attribs="fullname\,nickname\,email\,language"
# Set the allow-unverified config for U1.
fab manage:add_openid_rp_config,{u1.url},--allow-unverified,--allowed-user-attribs="fullname\,nickname\,email\,language"
# Add the API user for U1.
# We generated this json file with:
# $ fab manage:createsuperuser
# Go to {sso.url}/admin
# Sign in with the super user you have just created.
# Click the more link next to the Model Admin heading.
# On the Identityprovider section, click the +Add link next to API Users.
# Fill the form with:
# username: u1qauser
# password: u1qapassword
# Click the Save button.
# $ fab manage:dumpdata,identityprovider.APIUser
cat <<EOF >identityprovider/fixtures/apiuser.json
[
    {
        "pk": 1,
        "model": "identityprovider.apiuser",
        "fields": {
            "username": "u1qauser",
            "created_at": "2013-04-14 21:09:43",
            "password": "k1B7nUTaEsrqAPHF/bWsLlNIPUsH7mViraFQBZPgNRRuvsZlRq8CZg==",
            "updated_at": "2013-04-14 21:09:43"
        }
    }
]

EOF
fab manage:loaddata,apiuser
# Start the SSO server, accessible from the local network.
fab run:0.0.0.0:{sso.port}
