#!/bin/sh

# FIXME: This should run on the host and get config options expanded
# -- vila 2013-03-12

cd {sso.src_dir}

# get gargoyle flags from their use in the code
SST_FLAGS=`grep -rho --exclude 'test_*.py' "is_active([\"']\(.*\)[\"']" identityprovider/ webui/ | sed -E "s/is_active\(['\"](.*)['\"]/\1/" | awk '{print tolower($0)}' | sort | uniq | tr '\n' ';'`
# run tests                                                                    
SST_BASE_URL={sso.url} fab acceptance:screenshot=true,report=xml,extended=true,flags=$SST_FLAGS
